#!/bin/bash

date '+%T [%a] %d-%b-%Y'
date '+%T [%a] %d-%b-%Y'
awk 'BEGIN {
    srand()
    minval = 0x80
    maxval = 0x100 - minval
    red   = int(rand() * maxval)
    green = int(rand() * maxval)
    blue  = maxval - (red + green) / 2
    printf "#%02x%02x%02x\n", red + minval, green + minval, blue + minval
}'

case $BLOCK_BUTTON in
    1) notify-send "$(ncal -Mhb)";;
esac
