#!/bin/bash

date '+%d-%m-%y %H:%M:%S'
date '+%d-%m-%y %H:%M:%S'
awk 'BEGIN {
    srand()
    minval = 0xa0
    maxval = 0x100 - minval
    for (i = 0; i < 3; ++i)
        s = sprintf("%s%02x", s, int(minval + rand() * maxval))
    printf "#%s\n", s
}'

case $BLOCK_BUTTON in
    1) notify-send "$(ncal -Mhb)";;
esac
