#!/bin/bash

date '+%d-%m-%y %H:%M:%S'
date '+%d-%m-%y %H:%M:%S'
echo "$(cat /dev/urandom | tr -dc '0-9a-f' | head -c 6 | awk '{ printf "#%06x", 0xc0c0c0 + strtonum("0x"$1) % 0x303030}')"

case $BLOCK_BUTTON in
    1) notify-send "$(ncal -Mhb)";;
esac
