#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"

awk -v type=$TYPE '
function gb(v) { return v/1024/1024 }
function color(c, t) { return "<span foreground=\"" c "\">" t "</span>" }
function y(text) { return color("#ffff40", text) }
function b(text) { return color("#20baff", text) }
function g(text) { return color("#00ff00", text) }

/^Mem:/ {
	mem_total=$2
	mem_used=$3
	mem_free=$4
	mem_cache=$6
}

/^Swap:/ {
	swap_total=$2
	swap_used=$3
	swap_free=$4
}

END {
	# full text
	if (type == "swap")
		printf(y("U: %.1fG") "\n", gb(swap_used))
	else
		printf(y("U: %.1fG") " / " b("C: %.1fG") " / " g("T: %.1fG") "\n", gb(mem_used), gb(mem_cache), gb(mem_total))

	# TODO: short text

	# TODO: color (if less than X%)
}
' <(free -k)
